import { Company } from './types';

export const COMPANIES: Company[] = [
  {
    ticker: 'ADM',
    name: 'Archer-Daniels-Midland',
    sector: 'food-manufacturer',
    country: 'US',
    description:
      'One of the world\'s largest agricultural processors and food ingredient providers, operating across oilseeds, corn processing, and nutrition segments.',
    esg: {
      overall: 58,
      environmental: 52,
      social: 61,
      governance: 62,
      rating: 'BBB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 6.2,
      scope2: 2.1,
      scope3: 38.5,
      carbonIntensity: 57.3,
      renewableEnergy: 18,
      netZeroTarget: 2050,
      cdpScore: 'B',
    },
  },
  {
    ticker: 'NSRGY',
    name: 'Nestlé',
    sector: 'food-manufacturer',
    country: 'CH',
    description:
      'The world\'s largest food and beverage company, with brands spanning coffee, dairy, nutrition, and pet food across 186 countries.',
    esg: {
      overall: 74,
      environmental: 72,
      social: 76,
      governance: 73,
      rating: 'AA',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 3.8,
      scope2: 1.2,
      scope3: 92.4,
      carbonIntensity: 38.1,
      renewableEnergy: 52,
      netZeroTarget: 2050,
      cdpScore: 'A-',
    },
  },
  {
    ticker: 'UL',
    name: 'Unilever',
    sector: 'food-manufacturer',
    country: 'GB',
    description:
      'A global consumer goods company with a portfolio of food, home care, and personal care brands, known for its sustainability commitments.',
    esg: {
      overall: 79,
      environmental: 81,
      social: 78,
      governance: 77,
      rating: 'AA',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 2.1,
      scope2: 0.9,
      scope3: 57.8,
      carbonIntensity: 28.4,
      renewableEnergy: 68,
      netZeroTarget: 2039,
      cdpScore: 'A',
    },
  },
  {
    ticker: 'GIS',
    name: 'General Mills',
    sector: 'food-manufacturer',
    country: 'US',
    description:
      'A leading global food company that manufactures and markets branded consumer foods, including Cheerios, Häagen-Dazs, and Nature Valley.',
    esg: {
      overall: 63,
      environmental: 60,
      social: 65,
      governance: 64,
      rating: 'BBB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 1.4,
      scope2: 0.8,
      scope3: 22.1,
      carbonIntensity: 41.2,
      renewableEnergy: 35,
      netZeroTarget: 2050,
      cdpScore: 'B',
    },
  },
  {
    ticker: 'TSN',
    name: 'Tyson Foods',
    sector: 'food-manufacturer',
    country: 'US',
    description:
      'One of the world\'s largest food companies, producing approximately 20% of US beef, pork, and chicken, with significant environmental footprint.',
    esg: {
      overall: 38,
      environmental: 28,
      social: 44,
      governance: 42,
      rating: 'BB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 8.7,
      scope2: 2.3,
      scope3: 54.6,
      carbonIntensity: 98.4,
      renewableEnergy: 12,
      netZeroTarget: 2050,
      cdpScore: 'C',
    },
  },
  {
    ticker: 'CAG',
    name: 'Conagra Brands',
    sector: 'food-manufacturer',
    country: 'US',
    description:
      'A leading branded food company with a portfolio of iconic brands including Healthy Choice, Birds Eye, and Duncan Hines.',
    esg: {
      overall: 55,
      environmental: 51,
      social: 57,
      governance: 58,
      rating: 'BBB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 1.1,
      scope2: 0.7,
      scope3: 18.3,
      carbonIntensity: 49.7,
      renewableEnergy: 22,
      netZeroTarget: 2050,
      cdpScore: 'B-',
    },
  },
  {
    ticker: 'PEP',
    name: 'PepsiCo',
    sector: 'food-manufacturer',
    country: 'US',
    description:
      'A global leader in food and beverages with iconic brands including Lay\'s, Doritos, Quaker, Gatorade, and Pepsi, generating over $93B in annual revenue across 200+ countries.',
    esg: {
      overall: 71,
      environmental: 68,
      social: 74,
      governance: 70,
      rating: 'AA',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 3.2,
      scope2: 1.4,
      scope3: 68.4,
      carbonIntensity: 34.2,
      renewableEnergy: 44,
      netZeroTarget: 2040,
      cdpScore: 'A-',
    },
  },
  {
    ticker: 'BUD',
    name: 'Anheuser-Busch InBev',
    sector: 'food-manufacturer',
    country: 'BE',
    description:
      'The world\'s largest brewer, producing over 500 beer brands including Budweiser, Corona, and Stella Artois, with operations in 50 countries and $59B in annual revenue.',
    esg: {
      overall: 59,
      environmental: 56,
      social: 61,
      governance: 59,
      rating: 'BBB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 2.8,
      scope2: 1.1,
      scope3: 31.7,
      carbonIntensity: 47.3,
      renewableEnergy: 51,
      netZeroTarget: 2040,
      cdpScore: 'A-',
    },
  },
  {
    ticker: 'KO',
    name: 'Coca-Cola',
    sector: 'food-manufacturer',
    country: 'US',
    description:
      'The world\'s largest non-alcoholic beverage company, with a portfolio of over 200 brands including Coca-Cola, Sprite, Fanta, and Powerade, sold in more than 200 countries.',
    esg: {
      overall: 68,
      environmental: 65,
      social: 70,
      governance: 68,
      rating: 'A',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 1.4,
      scope2: 0.8,
      scope3: 38.2,
      carbonIntensity: 31.8,
      renewableEnergy: 38,
      netZeroTarget: 2050,
      cdpScore: 'A-',
    },
  },
  {
    ticker: 'MDLZ',
    name: 'Mondelez International',
    sector: 'food-manufacturer',
    country: 'US',
    description:
      'A global snacking powerhouse with brands including Oreo, Cadbury, Toblerone, and Trident, generating $38B+ in annual revenue with 75% from outside the United States.',
    esg: {
      overall: 62,
      environmental: 60,
      social: 64,
      governance: 62,
      rating: 'BBB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 0.7,
      scope2: 0.4,
      scope3: 19.8,
      carbonIntensity: 51.4,
      renewableEnergy: 29,
      netZeroTarget: 2050,
      cdpScore: 'B',
    },
  },
  {
    ticker: 'DANOY',
    name: 'Danone',
    sector: 'food-manufacturer',
    country: 'FR',
    description:
      'A French multinational specializing in dairy, plant-based products, early life nutrition, and medical nutrition under brands including Activia, Evian, and Nutricia.',
    esg: {
      overall: 76,
      environmental: 78,
      social: 75,
      governance: 74,
      rating: 'AA',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 1.6,
      scope2: 0.7,
      scope3: 34.5,
      carbonIntensity: 39.2,
      renewableEnergy: 56,
      netZeroTarget: 2050,
      cdpScore: 'A',
    },
  },
  {
    ticker: 'KHC',
    name: 'Kraft Heinz',
    sector: 'food-manufacturer',
    country: 'US',
    description:
      'One of the largest food and beverage companies in North America, with iconic brands including Heinz, Kraft, Oscar Mayer, and Philadelphia cream cheese.',
    esg: {
      overall: 48,
      environmental: 44,
      social: 51,
      governance: 49,
      rating: 'BB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 0.8,
      scope2: 0.5,
      scope3: 14.7,
      carbonIntensity: 58.8,
      renewableEnergy: 19,
      netZeroTarget: 2050,
      cdpScore: 'B-',
    },
  },
  {
    ticker: 'ASBFY',
    name: 'Associated British Foods',
    sector: 'food-manufacturer',
    country: 'GB',
    description:
      'A diversified international food, ingredients, and retail group whose food businesses include Primark, AB Sugar, Twinings, Ovaltine, and Kingsmill bread.',
    esg: {
      overall: 57,
      environmental: 54,
      social: 59,
      governance: 57,
      rating: 'BBB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 1.2,
      scope2: 0.6,
      scope3: 11.4,
      carbonIntensity: 51.8,
      renewableEnergy: 26,
      netZeroTarget: 2050,
      cdpScore: 'B',
    },
  },
  {
    ticker: 'PPC',
    name: "Pilgrim's Pride",
    sector: 'food-manufacturer',
    country: 'US',
    description:
      'One of the largest chicken producers in the world, processing and selling fresh, frozen, and value-added chicken products to retailers, foodservice operators, and distributors.',
    esg: {
      overall: 41,
      environmental: 33,
      social: 46,
      governance: 43,
      rating: 'BB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 3.8,
      scope2: 0.9,
      scope3: 24.1,
      carbonIntensity: 89.4,
      renewableEnergy: 10,
      netZeroTarget: null,
      cdpScore: 'C',
    },
  },
  {
    ticker: 'KDP',
    name: 'Keurig Dr Pepper',
    sector: 'food-manufacturer',
    country: 'US',
    description:
      'A leading beverage company in North America with a portfolio of over 125 owned, licensed, or partner brands including Dr Pepper, Canada Dry, Green Mountain Coffee, and Snapple.',
    esg: {
      overall: 56,
      environmental: 52,
      social: 58,
      governance: 57,
      rating: 'BBB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 0.3,
      scope2: 0.2,
      scope3: 8.9,
      carbonIntensity: 63.6,
      renewableEnergy: 24,
      netZeroTarget: 2050,
      cdpScore: 'B-',
    },
  },
  {
    ticker: 'HRL',
    name: 'Hormel Foods',
    sector: 'food-manufacturer',
    country: 'US',
    description:
      'A global branded food company with products in more than 80 countries under brands including SPAM, Skippy, Planters, Applegate, and Jennie-O turkey products.',
    esg: {
      overall: 54,
      environmental: 50,
      social: 57,
      governance: 55,
      rating: 'BBB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 0.6,
      scope2: 0.3,
      scope3: 9.1,
      carbonIntensity: 75.2,
      renewableEnergy: 17,
      netZeroTarget: 2050,
      cdpScore: 'C',
    },
  },
  {
    ticker: 'CTVA',
    name: 'Corteva',
    sector: 'ag-chemical',
    country: 'US',
    description:
      'A leading global provider of seed and crop protection products, spun off from DowDuPont in 2019, focused on sustainable agriculture.',
    esg: {
      overall: 61,
      environmental: 58,
      social: 63,
      governance: 62,
      rating: 'BBB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 1.8,
      scope2: 0.6,
      scope3: 12.4,
      carbonIntensity: 44.6,
      renewableEnergy: 28,
      netZeroTarget: 2050,
      cdpScore: 'B',
    },
  },
  {
    ticker: 'BAYRY',
    name: 'Bayer AG',
    sector: 'ag-chemical',
    country: 'DE',
    description:
      'A life science company with operations in pharmaceuticals and agriculture, including the Crop Science division after acquiring Monsanto in 2018.',
    esg: {
      overall: 57,
      environmental: 54,
      social: 59,
      governance: 56,
      rating: 'BBB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 3.1,
      scope2: 1.4,
      scope3: 28.7,
      carbonIntensity: 52.1,
      renewableEnergy: 34,
      netZeroTarget: 2050,
      cdpScore: 'B',
    },
  },
  {
    ticker: 'FMC',
    name: 'FMC Corporation',
    sector: 'ag-chemical',
    country: 'US',
    description:
      'An agricultural sciences company providing crop protection, plant health, and pest & turf management products for farmers worldwide.',
    esg: {
      overall: 64,
      environmental: 62,
      social: 65,
      governance: 65,
      rating: 'BBB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 0.4,
      scope2: 0.2,
      scope3: 5.8,
      carbonIntensity: 35.2,
      renewableEnergy: 31,
      netZeroTarget: 2035,
      cdpScore: 'B',
    },
  },
  {
    ticker: 'NTR',
    name: 'Nutrien',
    sector: 'ag-chemical',
    country: 'CA',
    description:
      'The world\'s largest producer of potash and a major producer of nitrogen and phosphate fertilizers, serving growers across six continents.',
    esg: {
      overall: 52,
      environmental: 45,
      social: 56,
      governance: 55,
      rating: 'BB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 12.4,
      scope2: 3.1,
      scope3: 31.2,
      carbonIntensity: 72.8,
      renewableEnergy: 16,
      netZeroTarget: 2050,
      cdpScore: 'C',
    },
  },
  {
    ticker: 'CF',
    name: 'CF Industries',
    sector: 'ag-chemical',
    country: 'US',
    description:
      'A leading global manufacturer and distributor of hydrogen and nitrogen products for energy, fertilizer, emissions abatement, and other applications.',
    esg: {
      overall: 44,
      environmental: 36,
      social: 49,
      governance: 47,
      rating: 'BB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 11.8,
      scope2: 1.9,
      scope3: 19.4,
      carbonIntensity: 118.3,
      renewableEnergy: 8,
      netZeroTarget: 2050,
      cdpScore: 'C',
    },
  },
  {
    ticker: 'BG',
    name: 'Bunge',
    sector: 'commodity-trader',
    country: 'US',
    description:
      'A leading global agribusiness and food company operating along the entire grain and oilseed supply chain, from farm to consumer.',
    esg: {
      overall: 49,
      environmental: 44,
      social: 52,
      governance: 51,
      rating: 'BB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 4.9,
      scope2: 1.8,
      scope3: 87.3,
      carbonIntensity: 63.4,
      renewableEnergy: 21,
      netZeroTarget: 2050,
      cdpScore: 'B-',
    },
  },
  {
    ticker: 'GLNCY',
    name: 'Glencore',
    sector: 'commodity-trader',
    country: 'CH',
    description:
      'One of the world\'s largest commodity trading and mining companies, with significant exposure to agricultural products through its trading operations.',
    esg: {
      overall: 31,
      environmental: 24,
      social: 35,
      governance: 34,
      rating: 'B',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 36.8,
      scope2: 5.2,
      scope3: 148.6,
      carbonIntensity: 142.7,
      renewableEnergy: 6,
      netZeroTarget: 2050,
      cdpScore: 'D',
    },
  },
  {
    ticker: 'MOS',
    name: 'Mosaic Company',
    sector: 'commodity-trader',
    country: 'US',
    description:
      'The world\'s largest integrated producer of concentrated phosphate and potash, supplying fertilizers and feed ingredients to agricultural markets.',
    esg: {
      overall: 46,
      environmental: 39,
      social: 50,
      governance: 49,
      rating: 'BB',
      lastUpdated: '2024-09-01',
    },
    climate: {
      scope1: 5.6,
      scope2: 2.4,
      scope3: 24.8,
      carbonIntensity: 84.1,
      renewableEnergy: 14,
      netZeroTarget: 2040,
      cdpScore: 'C',
    },
  },
];

export const TICKERS = COMPANIES.map((c) => c.ticker);

export function getCompany(ticker: string): Company | undefined {
  return COMPANIES.find((c) => c.ticker === ticker.toUpperCase());
}

export function getCompaniesBySector(sector: Company['sector']): Company[] {
  return COMPANIES.filter((c) => c.sector === sector);
}

export const SECTOR_LABELS: Record<Company['sector'], string> = {
  'food-manufacturer': 'Food Manufacturer',
  'ag-chemical': 'Ag Chemical',
  'commodity-trader': 'Commodity Trader',
};
